In [3]:
import pandas as pd

In [4]:
# Read Data From Google Drive
data = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/electricity consumption2.xlsx")

In [6]:
data.head()

,Meter_ID,Reading_Date,Area,Customer_Type,Units_kWh,Tariff_per_kWh,Payment_Status,Total Revenue
0,MTR0003,2025-07-29,Mogadishu,Commercial,1955.8,0.212,Paid,414.6296
1,MTR0004,2025-02-11,Baidoa,Commercial,1900.5,0.225,Paid,427.6125
2,MTR0005,2025-03-01,Kismayo,Commercial,1713.4,0.216,Paid,370.0944
3,MTR0014,2026-05-11,Mogadishu,Commercial,0.0,0.228,Pending,0.0000
4,MTR0015,2025-06-14,Baidoa,Commercial,2125.0,0.215,non_pay,456.8750

In [7]:
data.tail()

,Meter_ID,Reading_Date,Area,Customer_Type,Units_kWh,Tariff_per_kWh,Payment_Status,Total Revenue
295,MTR0249,2026-03-01,Kismayo,non_customer,3446.1,0.252,Overdue,868.4172
296,MTR0250,2025-08-09,Garowe,non_customer,699.7,0.223,Pending,156.0331
297,MTR0284,2025-04-02,Hargeisa,non_customer,989.4,0.223,pending,220.6362
298,MTR0299,2025-10-30,Mogadishu,non_customer,529.7,0.186,Pending,98.5242
299,MTR0300,2025-10-04,Bosaso,non_customer,4843.1,0.253,Paid,1225.3043

In [8]:
data.sample(5)

,Meter_ID,Reading_Date,Area,Customer_Type,Units_kWh,Tariff_per_kWh,Payment_Status,Total Revenue
204,MTR0172,2025-10-17,Bosaso,Residential,212.1,0.189,Paid,40.0869
71,MTR0286,2026-07-11,Baidoa,Commercial,1425.9,0.217,Paid,309.4203
189,MTR0148,2025-05-22,Baidoa,Residential,356.3,0.188,Pending,66.9844
3,MTR0014,2026-05-11,Mogadishu,Commercial,0.0,0.228,Pending,0.0000
203,MTR0171,2025-10-16,Mogadishu,Residential,349.4,0.182,Paid,63.5908

In [9]:
data.shape

(300, 8)

In [11]:
data.columns

Index(['Meter_ID', 'Reading_Date', 'Area', 'Customer_Type', 'Units_kWh',
       'Tariff_per_kWh', 'Payment_Status', 'Total Revenue'],
      dtype='object')

In [12]:
data.dtypes

Meter_ID                  object
Reading_Date      datetime64[ns]
Area                      object
Customer_Type             object
Units_kWh                float64
Tariff_per_kWh           float64
Payment_Status            object
Total Revenue            float64
dtype: object

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Meter_ID        300 non-null    object
 1   Reading_Date    300 non-null    datetime64[ns]
 2   Area            300 non-null    object
 3   Customer_Type   300 non-null    object
 4   Units_kWh       300 non-null    float64
 5   Tariff_per_kWh  300 non-null    float64
 6   Payment_Status  300 non-null    object
 7   Total Revenue   300 non-null    float64
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 18.9+ KB

In [15]:
data.describe(include="all")

,Meter_ID,Reading_Date,Area,Customer_Type,Units_kWh,Tariff_per_kWh,Payment_Status,Total Revenue
count,300,300,300,300,300.000000,300.000000,300,300.000000
unique,300,NaN,9,4,NaN,NaN,7,NaN
top,MTR0300,NaN,Mogadishu,Residential,NaN,NaN,Paid,NaN
freq,1,NaN,98,187,NaN,NaN,187,NaN
mean,NaN,2025-10-17 08:04:48,NaN,NaN,974.805667,0.227757,NaN,185.511930
min,NaN,2025-01-01 00:00:00,NaN,NaN,0.000000,-10.000000,NaN,-5979.000000
25%,NaN,2025-06-18 18:00:00,NaN,NaN,238.600000,0.177750,NaN,34.138650
50%,NaN,2025-10-21 00:00:00,NaN,NaN,468.600000,0.184000,NaN,77.804850
75%,NaN,2026-02-17 06:00:00,NaN,NaN,1005.325000,0.216250,NaN,206.666700
max,NaN,2026-08-01 00:00:00,NaN,NaN,10022.000000,23.000000,NaN,1881.504000
std,NaN,NaN,NaN,NaN,1482.763413,1.445218,NaN,503.597106